sonar.projectKey=nivada12
sonar.organization=nivada12
sonar.projectName=Playwright Login Test
sonar.projectVersion=1.0

# Sources à analyser
sonar.sources=.
sonar.exclusions=node_modules/**,test-results/**,playwright-report/**

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info